# Generated by Django 5.1.6 on 2025-02-14 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True)),
                ('ano_ingresso', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=60, null=True)),
                ('nivelQNQP', models.CharField(blank=True, max_length=30, null=True)),
                ('creditos', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('bimestre', models.CharField(blank=True, max_length=30, null=True)),
                ('avaliador', models.CharField(blank=True, max_length=100, null=True)),
                ('data_assinatura_avaliador', models.DateField(blank=True, null=True)),
                ('verificador_interno', models.CharField(blank=True, max_length=100, null=True)),
                ('data_assinatura_verificador', models.DateField(blank=True, null=True)),
                ('data_assinatura_estudante', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ano_ingresso', models.IntegerField()),
                ('nome_do_centro', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_do_centro', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('nome', models.CharField(max_length=100)),
                ('data_avaliacao', models.DateField(blank=True, null=True)),
                ('data_reavaliacao1', models.DateField(blank=True, null=True)),
                ('data_reavaliacao2', models.DateField(blank=True, null=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultados_estudantes.modulo')),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultado_avaliacao', models.CharField(blank=True, choices=[('A', 'Admitido(A)'), ('NA', 'Nao Admitido(NA)'), ('WD', 'Nao Fez Avaliacao(WD)'), ('', 'Nenhum Resultado')], max_length=10, null=True)),
                ('resultado_reavaliacao1', models.CharField(blank=True, choices=[('A', 'Admitido(A)'), ('NA', 'Nao Admitido(NA)'), ('WD', 'Nao Fez Avaliacao(WD)'), ('', 'Nenhum Resultado')], max_length=10, null=True)),
                ('resultado_reavaliacao2', models.CharField(blank=True, choices=[('A', 'Admitido(A)'), ('NA', 'Nao Admitido(NA)'), ('WD', 'Nao Fez Avaliacao(WD)'), ('', 'Nenhum Resultado')], max_length=10, null=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultados_estudantes.avaliacao')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultados_estudantes.estudante')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoAprendizagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('numero', models.PositiveSmallIntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultados_estudantes.modulo')),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='resultado_aprendizagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultados_estudantes.resultadoaprendizagem'),
        ),
        migrations.AddField(
            model_name='modulo',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultados_estudantes.turma'),
        ),
        migrations.AddField(
            model_name='estudante',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resultados_estudantes.turma'),
        ),
    ]
